select * from users;

DROP TABLE IF EXISTS TODO;
CREATE TABLE TODO (
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512) NULL,
    DONE BOOLEAN,
    USERID VARCHAR(12) NOT NULL,
    FOREIGN KEY (USERID) REFERENCES USERS(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

INSERT INTO TODO(TITLE, DESCRIPTION, DONE, USERID)
VALUES ('야구장', '프로야구 경기 보기', FALSE, 'GUEST'),
       ('놀기', '열심히 놀기', FALSE, 'GUEST'),
       ('DB공부', 'JDBC 모듈평가 공부', FALSE, 'MEMBER'),
       ('코테', '알고리즘 공부', TRUE, 'GUEST');

SELECT * FROM TODO;